system("grep '^[12]/2/2007' household_power_consumption.txt >> input.txt")
data <- read.table("input.txt",sep = ";", header = FALSE,colClasses = c("character","character","numeric","numeric","numeric","numeric","numeric","numeric","numeric"),na.strings = "?")
names(data) <- c("Date","Time","Global_active_power","Global_reactive_power","Voltage","Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3")
data["datetime"] <- as.POSIXct(paste(as.Date(data$Date,format="%d/%m/%Y"), data$Time), format="%Y-%m-%d %H:%M:%S")
par(mfrow=c(2,2))
with(data, {
    plot(datetime,Global_active_power,xlab="",ylab="Global Active Power",type = "l")
    plot(datetime,Voltage,xlab="datetime",ylab="Voltage",type = "l")
    plot(datetime,Sub_metering_1,type="l",xlab="",ylab = "Energy Sub Metering")
    lines(datetime,Sub_metering_2,col="Red")
    lines(datetime,Sub_metering_3,col="Blue")
    legend("topright", legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col = c("black", "red", "blue"), lwd = 2,bty = "n")
    plot(datetime,Global_reactive_power,xlab="datetime",ylab = "Global_reactive_power",type="l")
})
dev.copy(png,filename="plot4.png")
dev.off()