system("grep '^[12]/2/2007' household_power_consumption.txt >> input.txt")
data <- read.table("input.txt",sep = ";", header = FALSE,colClasses = c("character","character","numeric","numeric","numeric","numeric","numeric","numeric","numeric"),na.strings = "?")
names(data) <- c("Date","Time","Global_active_power","Global_reactive_power","Voltage","Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3")
data["datetime"] <- as.POSIXct(paste(as.Date(data$Date,format="%d/%m/%Y"), data$Time), format="%Y-%m-%d %H:%M:%S")
png(file ="plot3.png")
plot(data$datetime,data$Sub_metering_1,type="l",xlab="",ylab = "Energy Sub Metering")
lines(data$datetime,data$Sub_metering_2,col="Red")
lines(data$datetime,data$Sub_metering_3,col="Blue")
legend("topright", legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col = c("black", "red", "blue"), lwd = 2)
dev.off()